name: frontend

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: aws s3 sync . s3://gha-practice-rsakon --exact-timestamps --region ap-northeast-1